version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sonardb
      TZ: Asia/Ho_Chi_Minh
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]
    environment:
      TZ: Asia/Ho_Chi_Minh

  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      TZ: Asia/Ho_Chi_Minh
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes: [minio_data:/data]

volumes:
  pgdata:
  minio_data: